name: Deploy

on:
  workflow_call:
  push:
    branches: [ master ]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  CDK_DISABLE_TELEMETRY: 1

permissions:
  contents: read
  id-token: write

concurrency:
  group: 'deploy-infra'
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy infrastructure to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Validate trigger
        run: |
          echo "Workflow triggered by ${{ github.event.repository.full_name }}"
          case "${{ github.event.repository.full_name }}" in
            glotticaorg/glottica-backend|glotticaorg/glottica-frontend|glotticaorg/glottica-infra)
              echo "Triggered by authorized caller, succeeding"
              exit 0
              ;;
            *)
              echo "Triggered by unauthorized caller, failing"
            ;;
          esac
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: glotticaorg/glottica-infra

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build CDK app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Deploy
        run: |
          npx cdk deploy \
            --all \
            --require-approval never
